### ISSUE TITLE
Minimap Icons do not Render

### ISSUE THREAD

**Issue by ericellb** [TehCheat/PoEHelper#13]
The Minimap icons in PoeHelper do not render on the minimap or the large map.

I remember this breaking in the update from March 27th. Perhaps the memory address for the monster location is incorrect, and was never changed,

Unfortunately I do not have any more information on this. I tried this on DirectX11 and Vulkan, does not seem like the issue is specific to either.

Good new is this works flawless on Vulkan.

**Comment by TehCheat** [comment]
March 27th? LuL

It's usually caused by a bug in the code. Toggling healthbars/iconbuilder/minimapicons on and then off usually fixes it. Basically when one turns off, it turns them all off.

Also, if you're using Vulkan mode, a lot of things are weird. Windowed Fullscreen no longer seems to work. Windowed mode still works. I even had it working in full screen where it wasn't actually Full Screen (I could see my task bar). It's a beta for a reason, I suppose.

**Comment by ericellb** [comment]
Yeah, I quit around that time, and never submitted a bug request.

It seems to work properly on Quin version of PoeHelper, I just rather use this one.

I'll try disabling/enabling and report back.

As far as the windows fullscreen, it seems like all overlays broke with Vulkan using that mode.

**Comment by TehCheat** [comment]
They work fine for me, and many, many others, which leads me to believe that the issue is on your side.

**Comment by ericellb** [comment]
Very weird then. 

I have a fresh install of PoE and your latest release. Monster Healthbars work, Icons don't work at all.

Unsure what other repro steps I can provide. If it works for you on your latest release I guess you can close this off.

**Comment by TehCheat** [comment]
Make sure in the minimap icons settings "Draw Monster" is checked. It's off by default (which is dumb, but I haven't bothered fixing it yet).

**Comment by ericellb** [comment]
@TehCheat Yeah, I had that on. I tried tweaking every single setting and wasn't able to get it to work.

I had it working flawlessly prior to that March 27 update, unsure if the change that broke it for me was on your end, or a memory address change, however, I can confirm it doesn't work for me, and a friend. Both of ours worked prior to that update.

Not sure how different the plugin you run vs Quin, however it works fine using his HUD.
