### ISSUE TITLE
Oils, Organs and Delerium Dont go into New Tabs

### ISSUE THREAD

**Issue by ericellb** [TehCheat/PoEHelper#16]
The Oils, Organs, and Delirium orbs do not go into the new tabs.

The debug log shows the following.
```
Want to drop N items
Error with inventory type: index 7 Or 8 OR 9 (Not sure what this index value means)
```

I'm assuming that it's checking the type of the tab.

If I can help get some index or values of these tabs let me know. Maybe you can just treat any tab that does not have an index that is valid as a normal tab?

**Comment by TehCheat** [comment]
Stash tabs were updated to work at least partially so this is fixed.
