### ISSUE TITLE
.exe don't open

### ISSUE THREAD

**Issue by SadicVicious** [TehCheat/PoEHelper#24]
i install all needed for Poehelper works. When i unzip arquives, the .exe image don't change for black  image [https://i.imgur.com/g6lc9Cz.png](url) , two clicks on .exe and nothing open. My windows is Windows 10 leaked by phoenix OS, don't have firewall, defense etc...
In ctrl alt del nothing appears, simply don't open...
Any idea?

**Comment by SadicVicious** [comment]
[https://i.imgur.com/hIbrg1J.png](url) standalone poe version

**Comment by TehCheat** [comment]
Use the OwnedCore thread for help setting up dependencies. This is for issues with the project, not issues with your PC.

**Comment by SadicVicious** [comment]
mann now i resolve, i reinstall Require Microsoft Visual C++ 2015 Redistributable .NET framework v.6.0 and install direct9
 Now workksss uhuul thx
