### ISSUE TITLE
Seems to autocrash

### ISSUE THREAD

**Issue by BonuxGH** [TehCheat/PoEHelper#25]
Hello

sorry to bother u but i could use some help
i start the poe stand alone game as a limited user
then i try to start the PoeHelper by  Loader.exe
the app seem to start i can see the green x icon in my tray but the moment i hover over it it autocloses/disapears
i tried runing normal and rining as admin it always autocloses
i dont get any error messages
do u have any idea why it would do that

thx
![poe helper](https://user-images.githubusercontent.com/120753852/208189672-49e474ff-5c6a-4923-ae0e-844540e90ca0.jpg)

**Comment by TehCheat** [comment]
Because your environment isn't set up correctly. Use the ownedcore thread for support, this is for issues with the tool, not issues with your environment.

**Comment by BonuxGH** [comment]
ok ill try to figure it out
thx
p.s.
i tried an old version of poe helper i had and that one does not crash but obivusily it dosent work with the latest game version
