### ISSUE TITLE
Cannot launch PoeHelper

### ISSUE THREAD

**Issue by davethecripple** [TehCheat/PoEHelper#3]
Hi. Getting an error when running the Loader:
Error in Core Constructor -> System.NullReferenceException: Object reference not set to an instance of an object.
   atExileCore.Core..ctor(RenderForm form) in
D:\Temp\pg\ea\Core\Core.cs:line 156

**Comment by Akigis** [comment]
Steam version?

**Comment by davethecripple** [comment]
Yeah I was using Steam version. I tried stand-alone and it worked perfectly. That was the problem!
