### ISSUE TITLE
[3.21] Crucible not updated

### ISSUE THREAD

**Issue by repiatx** [TehCheat/PoEHelper#31]
First of all Thank you for your hardwork.

Fallowing plugin not working in Crucible league;

1. BasicFlaskRoutine
2. Radar ( red dots not showin up )

can you fix theese please ?

**Comment by repiatx** [comment]
Youa re awesome man really thank you. I'm really thankfull. I will try my best to contribute afterwards.

**Comment by repiatx** [comment]
Pathways in the map ( purple and other color)  to object not swoing up.

**Comment by TehCheat** [comment]
radar is broken until later. pathways are part of radar. Disable radar.
