### ISSUE TITLE
PassiveSkillTreePlanter requires SkillTreeData.dat

### ISSUE THREAD

**Issue by zathrath03** [TehCheat/PoEHelper#4]
[SkillTreeData.txt](https://github.com/TehCheat/PoEHelper/files/4008498/SkillTreeData.txt)

PassiveSkillTreePlanter plugin requires SkillTreeData.dat. Attached here is the text file, updated for Metamorph. Just rename .txt to .dat and put in Plugins\Compiled\PassiveSkillTreePlanter directory.

**Comment by TehCheat** [comment]
Added, thanks.
