### ISSUE TITLE
nothing working

### ISSUE THREAD

**Issue by i9xgit** [TehCheat/PoEHelper#45]
i loaded up poe today and now nothing is working at all,  it was working earlier today but then it just randomly broke, i tried deleting it and reinstalling it from the github but still nothing,  tried running as admin

https://i.imgur.com/34Yg49g.jpeg
https://i.imgur.com/OxjkWoK.png

it isnt using my quick silver flask nor is it showing enemys on my map when both are enabled

**Comment by i9xgit** [comment]
update: preload alert seems to work but whatever shows the enemys on your map doesnt nor does the basic flask stuff https://i.imgur.com/vssPpxL.jpeg

**Comment by Poehelperdev** [comment]
Sorry for the confusion you have to run it from inside the poe folder now limited user was broken with the last update but no longer needed

**Comment by TehCheat** [comment]
Don't listen to this idiot...

**Comment by TehCheat** [comment]
His comment has been removed. He was impersonating me and giving false information.

I'll have a fix in a few minutes. And yes, limited user still works perfectly fine, please keep using it.

**Comment by TehCheat** [comment]
pushed offsets fix
