### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by i9xgit** [TehCheat/PoEHelper#46]
is there a way to make it so poehelper doesnt appear in screenshots/discord screenshare/obs recording? as i would like to use it without the potential risk of people seeing it when i screenshare due to it technically being against tos

**Comment by i9xgit** [comment]
bump

**Comment by i9xgit** [comment]
honestly, im mostly asking about erhm the radar module and enemy's on the map thingy just so i can screenshare in discord without people seeing that shit

**Comment by Lawnmoers** [comment]
Im pretty sure ExileAPI uses DirectX hooking which means the overlay is drawn directly inside the game. If that is the case than it would be impossible to exclude from discord screen shares without essentially rewriting the entire rendering part of the program.

**Comment by TehCheat** [comment]
ExileApi uses an overlay (SharpDX) to draw, it does not hook DirectX. As such, you can share/record just the PoE window and it will not share/record the ExileApi HUD. If you record/share the monitor/screen, it **will** record/share the ExileApi HUD.
