### ISSUE TITLE
BasicFlaskRoutine

### ISSUE THREAD

**Issue by seldaneg** [TehCheat/PoEHelper#48]
BasicFlaskRoutine does not appear to be loading. Autoflask does not work. 

![image](https://github.com/TehCheat/PoEHelper/assets/93472586/6f4ad161-f774-47df-a279-04d954064aed)
![image](https://github.com/TehCheat/PoEHelper/assets/93472586/292d902b-cd36-4dd6-a378-dc85a2a6e592)

**Comment by Lawnmoers** [comment]
At the bottom of the Plugins click on TreeRoutine.Routine.BasicFlaskRoutine.
