### ISSUE TITLE
exileapi crashing

### ISSUE THREAD

**Issue by i9xgit** [TehCheat/PoEHelper#50]
any time i open exile api it just crashes help ;-;

**Comment by repiatx** [comment]
actually im really looking forward for update. I wish i had help :)

**Comment by i9xgit** [comment]
it just does this but anytime i try tabbing into it or press f12 it just crashes

**Comment by i9xgit** [comment]
![image](https://github.com/TehCheat/PoEHelper/assets/21007114/5ca9667a-1e43-499f-92c4-f38da8cad217)

**Comment by mega2k0** [comment]
yes random crashes since i started playing 7 h ago

**Comment by i9xgit** [comment]
> yes random crashes since i started playing 7 h ago

nah mine wont even hook to the game just crashes as soon as i launch it :/

**Comment by repiatx** [comment]
guys we need helppp :)

**Comment by vanyagod** [comment]
poehelper dead? no updates

**Comment by TehCheat** [comment]
Go to the [OwnedCore](https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/1000594-exileapi-3-23-beyond-plugin-framework.html) thread for the latest version.
