### ISSUE TITLE
 I can't find a solution

### ISSUE THREAD

**Issue by KinGGxuy** [TehCheat/PoEHelper#57]
@TehCheat 
![dfgfhjkhjk](https://github.com/user-attachments/assets/62016441-75b5-4882-b89c-56c185be3299)
![image](https://github.com/user-attachments/assets/7b329be7-36d8-459c-93e6-ddb8af93a460)
Hello, please tell me the solution to this problem.

**Comment by TehCheat** [comment]
This repo isn't up to date. You should go to the ownedcore thread for the current league's version.
