### ISSUE TITLE
[request] Add Bone Armour to BuffUtil plugin

### ISSUE THREAD

**Issue by Murdoc84** [TehCheat/PoEHelper#6]
![image](https://user-images.githubusercontent.com/22428605/71656777-077b5680-2d3d-11ea-8b43-3a250d7819b7.png)
this skill is for necromancer only:
![image](https://user-images.githubusercontent.com/22428605/71656809-2f6aba00-2d3d-11ea-810f-5cbe2d83fd2e.png)

**Comment by TehCheat** [comment]
This should be an issue on the BuffUtil plugin. And then once that is updated, an issue to update the BuffUtil plugin would be appropriate here.
