### ISSUE TITLE
icon appears but nothing happens

### ISSUE THREAD

**Issue by jorge966** [TehCheat/PoEHelper#7]
do i need the password to unzip and use?

**Comment by SadicVicious** [comment]
same =[

**Comment by wdawdwdadad** [comment]
same =[

**Comment by TehCheat** [comment]
The public version is not yet updated for 3.10. I plan to update it next Monday.

**Comment by TehCheat** [comment]
And yes, to unzip the 3.10 file, you need the password.

**Comment by wdawdwdadad** [comment]
Can I get the password in advance for donation






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TehCheat"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 凌晨3:59
收件人: "TehCheat/PoEHelper"<PoEHelper@noreply.github.com&gt;; 
抄送: "aaaaaaaaaaa"<aabbpoe@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TehCheat/PoEHelper] icon appears but nothing happens (#7)





 
And yes, to unzip the 3.10 file, you need the password.

**Comment by wdawdwdadad** [comment]
Can I get the password in advance for donation

**Comment by jorge966** [comment]
okay thanks
