### ISSUE TITLE
still off?

### ISSUE THREAD

**Issue by SadicVicious** [TehCheat/PoEHelper#8]
have to pay for catch the updated poehelper? why don't have any post seeing this =[ 
for now i'm still use the wingman but i prefer poehelper =[ have to pay or not?

**Comment by jorge966** [comment]
he will make it public on monday, probs checking to see if everything is working and what is bricked so he an fix before he makes it public

**Comment by Xaaalera** [comment]
how i can pay PoeHud without paypal?

**Comment by TehCheat** [comment]
Public now. Closing...
